/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package DriverLesson1;

import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.edge.EdgeDriver;
import org.testng.Assert;
import org.testng.annotations.Test;

import io.github.bonigarcia.wdm.WebDriverManager;

public class LibraryTest {
	@Test
	public void launchDriver() {
		// declaration and instantiation of objects/variables
		//Step 1: Set driver's system property
    	WebDriverManager.edgedriver().setup(); 
    	
    	//Step 2: Intialize driver
		WebDriver driver = new EdgeDriver();
		
		//Step 3: Give a URL
        String baseUrl = "http://google.com";
        String expectedTitle = "Google";
        String actualTitle = "";

        // launch Chrome driver and direct it to the Base URL
        driver.get(baseUrl);
        driver.findElement(By.name("q")).sendKeys("Arijit Singh");
        // get the actual value of the title
        actualTitle = driver.getTitle();
        
        System.out.println(actualTitle);
        Assert.assertEquals(actualTitle, expectedTitle);
        driver.quit();


	}
	
	
	}
